POST https://fierce-crag-28247.herokuapp.com
/doctor HTTP/1.1
Content-Type: application/json

{
    "name":"",
    "specialization":"",
    "regno":"",
    "degree":"",
    "mob":"",
}

POST https://fierce-crag-28247.herokuapp.com
/patient HTTP/1.1
Content-Type: application/json

{
    "name":"",
    "dob":"",
    "patientno":"",
    "disease":"",
    "detail":[],
    "regno":"",
    "gender":"",
    "age":""
}

POST https://fierce-crag-28247.herokuapp.com
/patient/:12 HTTP/1.1
Content-Type: application/json

{
    "name":"",
    "dob":"",
    "patientno":"",
    "disease":"",
    "detail":[],
    "regno":"",
    "gender":"",
    "age":""
}

GET https://fierce-crag-28247.herokuapp.com
/patient HTTP/1.1

GET https://fierce-crag-28247.herokuapp.com
/patient/12 HTTP/1.1

GET https://fierce-crag-28247.herokuapp.com
/doctor HTTP/1.1

GET https://fierce-crag-28247.herokuapp.com
/doctor/12 HTTP/1.1


GET https://fierce-crag-28247.herokuapp.com
/user HTTP/1.1

GET https://fierce-crag-28247.herokuapp.com
/user/1 HTTP/1.1

POST https://fierce-crag-28247.herokuapp.com
/user/1 HTTP/1.1

POST https://fierce-crag-28247.herokuapp.com
/user HTTP/1.1
Content-Type: application/json

{
    "regno":"",
    "email":"",
    "password":"",
    "location":""
}

POST https://fierce-crag-28247.herokuapp.com
/admin HTTP/1.1
Content-Type: application/json

{
    "email":"rajiv@gmail.com",
    "password":"1234"
}

POST https://fierce-crag-28247.herokuapp.com
/admin/12 HTTP/1.1
Content-Type: application/json

{
    "email":"",
    "password":""
}

GET https://fierce-crag-28247.herokuapp.com
/admin HTTP/1.1

DELETE https://fierce-crag-28247.herokuapp.com
/patient/123 HTTP/1.1




